service: test-lambda

frameworkVersion: "2"

provider:
  name: aws
  stage: ${opt:stage}
  region: ap-southeast-1
  lambdaHashingVersion: 20201221
  memorySize: 1024
  timeout: 30
  apiName: ${self:service}-${opt:stage}
  apiGateway:
    description: REST API ${self:service}
    metrics: true

functions: ${file(functions.yml):functions}